### ISSUE TITLE
creating simulation from BC6.cell.nml gives hoc error

### ISSUE THREAD

**Issue by BKriener** [OpenSourceBrain/NorenbergEtAl2010_DGBasketCell#1]
Running CreateCellModel.py with BC2.cell.nml yields output BC2_na_k.hoc. Executing CreateNetwork.py (creating LEMS_Test.xml) with the respective cell model input and running the simulation with 
env JNML_MAX_MEMORY_LOCAL=2000M jnml LEMS_Test.xml -neuron -run -nogui
yields correct membrane potential traces.

However doing the same with the BC6.cell.nml instead rises the error 

(INFO) NRN Error  >>> /home/kriener/neuro/neuron-7.4/x86_64/bin/nrniv: pt3dadd call nested too deeply, increase with -NFRAME framesize option
(INFO) NRN Error  >>>  near line 1
(INFO) NRN Error  >>>  a_BC[0] = new BC6_na_k()
(INFO) NRN Error  >>>                          ^
(INFO) NRN Error  >>>         BC6_na_k[0].basic_shape_251()
(INFO) NRN Error  >>>       BC6_na_k[0].basic_shape_250()
(INFO) NRN Error  >>>     BC6_na_k[0].basic_shape_249()
(INFO) NRN Error  >>>   BC6_na_k[0].basic_shape_248()
(INFO) NRN Error  >>> and others
(INFO) NRN Error  >>> /home/kriener/neuro/neuron-7.4/x86_64/bin/nrniv: soma : object prefix is NULL
(INFO) NRN Error  >>>  near line 1
(INFO) NRN Error  >>>  access a_BC[0].soma
(INFO) NRN Error  >>>                     ^
(INFO) NRN Error  >>> /home/kriener/neuro/neuron-7.4/x86_64/bin/nrniv: position : object prefix is NULL
(INFO) NRN Error  >>>  near line 1
(INFO) NRN Error  >>>  { a_BC[0].position(0., 0., 0.) }
(INFO) NRN Error  >>>                                  ^
(INFO) NRN Error  >>> /home/kriener/neuro/neuron-7.4/x86_64/bin/nrniv: soma : object prefix is NULL
(INFO) NRN Error  >>>  near line 1
(INFO) NRN Error  >>>  a_BC[0].soma { stim0_input_0 = new stim0(0.024999948) } 
(INFO) NRN Error  >>>                                                          ^
(INFO) NRN Error  >>> /home/kriener/neuro/neuron-7.4/x86_64/bin/nrniv: syntax error
(INFO) NRN Error  >>>  near line 1
(INFO) NRN Output >>> first instance of n_BC
(INFO) NRN Output >>> Adding input list: stim0_input to BC, with 1 inputs of type stim0
(INFO) NRN Error  >>>   objectvar v_BC_0_BC6_na_k_0_v_BC6_na_k_voltages.dat 
(INFO) NRN Error  >>>                                                  ^
(INFO) NRN Error  >>> /home/kriener/neuro/neuron-7.4/x86_64/bin/nrniv: syntax error
(INFO) NRN Error  >>>  near line 1
(INFO) NRN Error  >>>   { v_BC_0_BC6_na_k_0_v_BC6_na_k_voltages.dat = new Vector() } 
(INFO) NRN Error  >>>                                          ^
(INFO) NRN Error  >>> /home/kriener/neuro/neuron-7.4/x86_64/bin/nrniv: syntax error
(INFO) NRN Error  >>>  near line 1
(INFO) NRN Error  >>>   { v_BC_0_BC6_na_k_0_v_BC6_na_k_voltages.dat.record(&a_BC[0].soma.v(0.024999948)) } 
(INFO) NRN Error  >>>                                          ^
(INFO) NRN Error  >>> Traceback (most recent call last):
(INFO) NRN Error  >>>   File "/home/kriener/NorenbergEtAl2010_DGBasketCell/NeuroML2/LEMS_Test_nrn.py", line 200, in <module>
(INFO) NRN Error  >>>     ns = NeuronSimulation(tstop=400, dt=0.025, seed=12345)
(INFO) NRN Error  >>>   File "/home/kriener/NorenbergEtAl2010_DGBasketCell/NeuroML2/LEMS_Test_nrn.py", line 104, in __init__
(INFO) NRN Error  >>>     h.v_BC_0_BC6_na_k_0_v_BC6_na_k_voltages.dat.resize((h.tstop * h.steps_per_ms) + 1)
(INFO) NRN Error  >>> AttributeError: 'hoc.HocObject' object has no attribute 'v_BC_0_BC6_na_k_0_v_BC6_na_k_voltages'
^C(INFO) NRN Error  >>> >>>

**Comment by pgleeson** [comment]
Looking into this... 
Basically it's due to being a v big cell and Neuron not liking the lines and lines of generated hoc file...
Do you need the whole cell including all of the axon? There seems to be quite a bit of variability in the radii used for the axon segments, not sure what effect this would have on the correct simulation of propagation of any APs in the axon...

**Comment by BKriener** [comment]
I don't explicitly need axons right now, they are just part of the cell. So functionally they are not needed.

**Comment by BKriener** [comment]
I now get the same problem with the smaller cell BC1 that I uploaded. Unfortunately, I need the axon as part of the cell, even though it functionally doesn't do much. Is there another (manual) fix?

**Comment by pgleeson** [comment]
Basically I'm not sure this can be done without updating the Neuron exporter from jNeuroML ([here I think](https://github.com/NeuroML/org.neuroml.export/blob/development/src/main/resources/neuron/cell.vm#L79)).. it just needs to handle the case when there's going to be many lines of hoc and break them up into multiple procedures. 

I'm afraid i won't be able to look at this before CNS, so unless there's anyone there who wants to dive in and fix it...

**Comment by pgleeson** [comment]
@BKriener Have started looking into this. But first needed to document the repo a bit and make the files more general for generating with different cells. Work in progress...

**Comment by pgleeson** [comment]
@BKriener I've added the BC6 example to the repo now. It can be generated and run with:

     jnml LEMS_Test_BC6.xml -neuron
     nrnivmodl 
     nrngui -NFRAME 3000  LEMS_Test_BC6_nrn.py 

i.e. the NFRAME option tells NEURON to increase the recursion depth size:

![shape zoom in-out x -449 7 540 8 y -438 108 603 108_910](https://user-images.githubusercontent.com/1556687/47714243-417e3380-dc34-11e8-9e2d-6b5157a5ceee.png)

**Comment by BKriener** [comment]
Great, that works, thanks!
